global:
  scrape_interval:     15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: sample-backend
    file_sd_configs:
      - files: [ '/etc/prometheus/service-discovery.json' ]
        refresh_interval: 15s

  - job_name: sun-exporter
    scrape_interval: 1m
    static_configs:
      - targets: [ 'sun-exporter:3000' ]
